name: Schedule Reddit Instagram Post

on:
  schedule:
    # Schedule to run at 6 PM UTC (you may need to adjust the time to your timezone)
    - cron: '0 13 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Specify your Python version here
      - name: Install dependencies
        run: |
          pip install praw requests instagrapi # Add other dependencies if needed
      - name: Run script
        run: python autogram.py # Replace with your script's filename
