name: Schedule Reddit Instagram Post

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subreddit: ['MoldyMemes', 'memes', 'okbuddyretard', 'animememes']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
      - name: Set up Git configuration
        run: |
          git config --global user.email "abdulsamad4576@gmail.com"
          git config --global user.name "Abdul Samad"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install praw requests pillow instagrapi
      - name: Run script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
        run: python autogram.py ${{ matrix.subreddit }}
