name: Schedule Reddit Instagram Post

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
      - name: Set up Git configuration
        run: |
          git config --global user.email "abdulsamad4576@gmail.com"
          git config --global user.name "Abdul Samad"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install praw requests pillow json
      - name: Run script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          INSTA_ACCESS_TOKEN: ${{ secrets.INSTA_ACCESS_TOKEN }}
          INSTA_USER_ID: ${{ secrets.INSTA_USERNAME }}
        run: python autogram.py
